apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-task
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/task"
