apiVersion: v1
kind: Deloyment
metadata:
  name: nginx-ns1
  labels:
    env: demo
spec:
  template:
    metadata:
      labels:
        env: demo
      name: nginx
    spec:
      containers:
        - image: nginx:1.23.4-alpine
          name: nginx
          ports:
            - containerPort: 80    