apiVersion: v1
kind: Pod
metadata:
  labels:
    test: both
  name: both
spec:
  containers:
    - name: both-containers
      image: registry.k8s.io/e2e-test-images/agnhost:2.40
      args:
        - liveness and readines
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 8
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 3
