apiVersion: v1
kind: Pod
metadata:
  name: multi-task
  labels:
    app: multi-task
spec:
  containers:
  - name: multi-task
    image: busybox
    command: ['sh', '-c']
    env:
      - name: NAME
        value: "Multi-task"
  initContainers:
   - name: init-mymultipod
     image: busybox:1.28
     command: ['sh','-c']
     args: ['until nslookup multiservice.default.svc.cluster.local; do echo wait for service to be up; sleep 2; done']
   - name: init-secondcontainer
     image: busybox
     command: ['sh', '-c']
     args: ['until nslookup mydb.default.svc.cluster.local; do echo wait for service to be up; sleep 2; done']
  
        