apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec:
  template:
    metadata:
      labels:
        env: demo
      name: nginx
    spec:
      containers:
        - image: nginx:1.23.4-alpine
          name: nginx
          ports:
            - containerPort: 80
  replicas: 2
  selector: 
    matchLabels:
      env: demo        